### ISSUE TITLE
function code is corrupted

### ISSUE THREAD

**Issue by redmunds** [davidderaedt/annotate-extension#1]
1. I start with this code:

```
function getHand(svgDoc, id)
{
}
```
1. If I put IP on line _before_ function definition, I get this:

```
/**
 * Description
 * @param {type} svgDoc Description
 * @param {type} id Description
 */
function getHand(svgDoc, id)
{
}
```
1. But, if I place IP at char 0 on same line as "function getHand(svgDoc, id)", that line of code is removed:

```
/**
 * Description
 * @param {type} svgDoc Description
 * @param {type} id Description
 */
{
}
```

Result:
My code is corrupted

Expected Result:
Code should not be removed. Either comment is added, or nothing.

**Comment by davidderaedt** [comment]
Fixed with latest version. Thanks!

**Comment by redmunds** [comment]
Verified fixed. Thanks!
