### ISSUE TITLE
shortcut interferes with native "delete line"

### ISSUE THREAD

**Issue by johnrc** [davidderaedt/annotate-extension#6]
The shortcut, `CTRL`+`SHIFT`+`D`, is already used natively by Brackets for "delete line." It's not a big deal just an observation.

**Comment by HamsterCoder** [comment]
I've noticed the same, I think going to the menu every time is a very long action. Please add a shorcut.

**Comment by davidderaedt** [comment]
I changed the default binding to Ctrl+Shift+C

**Comment by davidderaedt** [comment]
Update: the new default key binding is Ctrl+Alt+A

**Comment by HamsterCoder** [comment]
Thanks!
