### ISSUE TITLE
Ctrl + Alt + A doesnt work

### ISSUE THREAD

**Issue by RaketenRonny** [davidderaedt/annotate-extension#9]
and i have no clue why :-(
i am working on windows 7, current brackets sprint is 28.
Annotate form the Edit menu works.

**Comment by davidderaedt** [comment]
Thanks for reporting. I won't be able to test (hence fix it) on windows for some time.
In the meantime, you can modify this hotkey by yourself: open the annotate extension folder (help > show extensions folder) and edit main.js line 183. Then you can just relaunch Brackets.

**Comment by RaketenRonny** [comment]
you're welcome. thanks for your help.
I changed it to ctrl+alt+y and it works.
